workflows:
  ios-ad-hoc-build:
    name: iOS Ad-hoc Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      ios_signing:
        certificates:
          - SeuJurosBuild         # Reference Name do .p12 no Teams
        provisioning_profiles:
          - SemJurosBuild        # Reference Name do .mobileprovision no Teams

      vars:
        XCODE_WORKSPACE: "Runner"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.abarei.semjuros"

      xcode: latest
      cocoapods: default

    scripts:
      - name: Instalar dependências
        script: |
          pod install

      - name: Inicializar keychain
        script: |
          keychain initialize

      - name: Adicionar certificados
        script: |
          keychain add-certificates

      - name: Aplicar perfis no projeto
        script: |
          xcode-project use-profiles

      - name: Build IPA para distribuição ad-hoc
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE.xcworkspace" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
