workflows:
  ios-build:
    name: iOS Build Ad-Hoc
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        certificates:
          - SemJurosCert
        provisioning_profiles:
          - SemJurosBuild

      vars:
        XCODE_WORKSPACE: "Runner"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.abarei.semjuros"

    scripts:
      - name: Instalar dependências
        script: flutter pub get

      - name: Instalar CocoaPods e gerar .xcworkspace
        script: |
          cd ios && pod install

      - name: Verificar se o workspace existe
        script: |
          ls "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE.xcworkspace" || {
            echo "Workspace não encontrado!" && exit 1
          }

      - name: Inicializar keychain
        script: keychain initialize

      - name: Adicionar certificados
        script: keychain add-certificates

      - name: Aplicar perfis no projeto
        script: xcode-project use-profiles

      - name: Build IPA para distribuição ad-hoc
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE.xcworkspace" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist $CM_BUILD_DIR/ios/export_options.plist

