workflows:
  ios-build:
    name: iOS Build Ad-Hoc
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Instalar dependências
        script: flutter pub get

      - name: Inicializar keychain
        script: keychain initialize

      - name: Adicionar certificados
        script: keychain add-certificates

      - name: Aplicar perfis no projeto
        script: xcode-project use-profiles

      - name: Build IPA para distribuição ad-hoc
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE.xcworkspace" \
            --scheme "$XCODE_SCHEME"
