workflows:
   ios-build:
       name: iOS Build Ad-Hoc
       instance_type: mac_mini_m2

       environment:
            flutter: stable
            xcode: latest
            cocoapods: default

            vars:
              CERT_PASSWORD: I74sbHRX
              XCODE_WORKSPACE: "Runner"
              XCODE_SCHEME: "Runner"
              BUNDLE_ID: "com.abarei.semjuros"

       scripts:
       - name: Instalar dependências
         script: flutter pub get

       - name: Print Generated.xcconfig
         script: |
          cat ios/Flutter/Generated.xcconfig || echo "Arquivo não encontrado"

       - name: Importar certificado e perfil
         script: |
          # Importar certificado
          keychain add-certificates --certificate ios/semjuroscert.p12 --certificate-password $CERT_PASSWORD
    
          # Importar o provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ios/SemJurosBuild.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
            
       - name: Instalar CocoaPods e gerar .xcworkspace
         script: |
           cd ios && pod install

       - name: Verificar se o workspace existe
         script: |
          ls "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE.xcworkspace" || {
            echo "Workspace não encontrado!" && exit 1
          }

       - name: Inicializar keychain
         script: keychain initialize

       - name: Gerar ExportOptions.plist
         script: |
          cat <<EOF > $CM_BUILD_DIR/ios/export_options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>com.abarei.semjuros</key>
                <string>SemJurosBuild</string>
              </dict>
              <key>compileBitcode</key>
              <false/>
            </dict>
          </plist>
          EOF

       - name: Build IPA usando comando simplificado
         script: |
             set -eo pipefail
             xcodebuild \
               -workspace "ios/Runner.xcworkspace" \
               -scheme "Runner" \
               -archivePath "$CM_BUILD_DIR/ios/Runner.xcarchive" \
               archive \
               CODE_SIGN_IDENTITY="Apple Distribution" \
               CODE_SIGN_STYLE=Manual \
               | tee xcodebuild.log
               
       - name: Mostrar log do XcodeBuild
         script: cat xcodebuild.log



artifacts:
  - build/ios/ipa/*.ipa

