workflows:
  ios-build:
    name: iOS Build Ad-Hoc
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        certificates:
        - SemJurosCert:kSNAYlaA
        provisioning_profiles:
        - SemJurosBuild

      vars:
        XCODE_WORKSPACE: "Runner"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.abarei.semjuros"

    scripts:
      - name: Instalar dependências
        script: flutter pub get

      - name: Instalar CocoaPods e gerar .xcworkspace
        script: |
          cd ios && pod install

      - name: Verificar se o workspace existe
        script: |
          ls "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE.xcworkspace" || {
            echo "Workspace não encontrado!" && exit 1
          }

      - name: Inicializar keychain
        script: keychain initialize

      - name: Adicionar certificados manualmente
        script: |
          keychain add-certificates \
            --certificate-name SemJurosCert \
            --certificate-password 

      - name: Adicionar ExportOptions.plist
        script: |
          cat <<EOF > $CM_BUILD_DIR/ios/export_options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" 
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>signingCertificate</key>
              <string>Apple Distribution</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>com.abarei.semjuros</key>
                <string>SemJurosBuild</string>
              </dict>
              <key>compileBitcode</key>
              <false/>
            </dict>
          </plist>
          EOF

      - name: Archive Runner Manual
        script: |
          xcodebuild clean \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release
      
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            DEVELOPMENT_TEAM=V42F9XV6FV \
            PROVISIONING_PROFILE_SPECIFIER="SemJurosBuild"
      
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ipa

      - name: Build IPA para distribuição ad-hoc
        script: |
          xcode-project build-ipa --verbose \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE.xcworkspace" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist $CM_BUILD_DIR/ios/export_options.plist
